import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/components/navber-footer/Navber";
import ReduxProvider from "@/toolkit/ReduxProvider";
import SmoothScroll from "@/components/smoothScroll/SmoothScroll";
import Footer from "@/components/navber-footer/Footer";
import Overlay from "@/components/overlayDiv/Overlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pixio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SmoothScroll />
          <Navber />
          <div className="h-20" />
          {children}
          <Overlay />

          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
