import React from "react";
import fetchProduct from "@/components/landing/apis/dummy";
import FilterSide from "@/components/filter/FilterSide";
import ShowingProduct from "@/components/filter/ShowingProduct";
export const metadata = {
  title: "Shop Now",
  description: "Generated by create next app",
};

async function page() {
  const fetchFunc = async () => {
    const [smartPhones, laptops, decoration, automotive, motorcycle, lighting] =
      await Promise.all([
        fetchProduct("smartphones"),
        fetchProduct("laptops"),
        fetchProduct("home-decoration"),
        fetchProduct("automotive"),
        fetchProduct("motorcycle"),
        fetchProduct("lighting"),
      ]);

    return [
      ...smartPhones.products,
      ...laptops.products,
      ...decoration.products,
      ...automotive.products,
      ...motorcycle.products,
      ...lighting.products,
    ];
  };
  const data = await fetchFunc() || [];
  

  return (
    <div className=" max-w-[1800px] px-2 py-12 bg-[#FFFAF3] mx-auto">
      <div>
        {/* left */}
        <div className=" max-w-[400px]">
          {data.length > 0 && (
            <div>
              <FilterSide
                categories={[
                  ...new Set(
                    data.map(
                      (item) =>
                        item.category.slice(0, 1).toUpperCase() +
                        item.category.slice(1, item.category.length),
                    ),
                  ),
                  "All",
                ]}
                minPrice={400}
                maxPrice={1000}
              />
            </div>
          )}
        </div>
        {/* right */}
        <div>
          <ShowingProduct products = {data}/>
        </div>
      </div>
    </div>
  );
}

export default page;
