import React from "react";
import fetchProduct from "@/components/landing/apis/dummy";
import FilterSide from "@/components/filter/FilterSide";
import ShowingProduct from "@/components/filter/ShowingProduct";
export const metadata = {
  title: "Shop Now",
  description: "Generated by create next app",
};

function page() {
  return (
    <div className=" max-w-[1800px] px-2 py-12 bg-[#FFFAF3] mx-auto">
      <ShowingProduct
        categories={[
          "smartphones",
          "laptops",
          "fragrances",
          "skincare",
          "groceries",
          "home-decoration",
          "furniture",
          "tops",
          "womens-dresses",
          "womens-shoes",
          "mens-shirts",
          "mens-shoes",
          "mens-watches",
          "womens-watches",
          "womens-bags",
          "womens-jewellery",
          "sunglasses",
          "automotive",
          "motorcycle",
          "lighting",
        ]}
        text={"Shop Now"}
      />
    </div>
  );
}

export default page;
